### ISSUE TITLE
@itemmap 100 = crash

### ISSUE THREAD

**Issue by tlacson7** [dastgirp/HPM-Plugins#44]
```
#0  should_log_item (nameid=1658, amount=-100, refine_level=0, id=0x100)
    at log.c:117
        filter = 1658
#1  0x00000000004d030e in log_pick (id=150203, m=-100, type=LOG_TYPE_COMMAND,
    amount=-100, itm=0x9d4700 <log_s>, data=0x100) at log.c:214
No locals.
#2  0x00007ffff200e28b in pc_getitem_map (sd=0x1765a30, it=..., amt=100,
    count=100, log_type=LOG_TYPE_PRODUCE) at itemmap.c:74
        flag = 1
#3  0x00007ffff200ed51 in itemmap (fd=1658, sd=0xa3, command=0x0,
    message=0x64 <Address 0x64 out of bounds>, info=0x9d4700 <log_s>,
    get_type=-253939652) at itemmap.c:270
        item_name = "Blue_Potion", '\000' <repeats 88 times>
        party_name = '\000' <repeats 23 times>
        guild_name = '\000' <repeats 23 times>
        amount = 100
        get_count = 100
        i = 12925248
        m = 163
        it = {id = 0, nameid = 505, amount = 0, equip = 0,
          identify = 1 '\001', refine = 0 '\000', attribute = 0 '\000',
          card = {0, 0, 0, 0}, expire_time = 0, favorite = 0 '\000',
          bound = 0 '\000', unique_id = 0, option = {{index = 0, value = 0,
---Type <return> to continue, or q <return> to quit---
              param = 0 '\000'}, {index = 0, value = 0, param = 0 '\000'}, {
              index = 0, value = 0, param = 0 '\000'}, {index = 0, value = 0,
              param = 0 '\000'}, {index = 0, value = 0, param = 0 '\000'}}}
        item_data = 0x0
        p = 0x7ffff0dd303c
        g = 0x1765a30
        iter = 0x7ffff0dd303c
        pl_sd = 0x1765a30
#4  0x0000000000432840 in atcommand_exec (fd=11, sd=0x1765a30,
    message=0x7fffffffdd0a "@itemmap Blue_Potion 100", player_invoked=false)
    at atcommand.c:10843
        params = "Blue_Potion 100", '\000' <repeats 84 times>
        command = "@itemmap", '\000' <repeats 91 times>
        output = "\005\000\000\000\000\000\000\000\230\332\377\377\377\177\000\000d\213d\352\377\177\000\000\004\000\000\000\000\000\000\000\200\332\377\377\377\177\000\000\326\033N\000\000\000\000\000\360*M\000\000\000\000\000d\213d\352\377\177\000\000\n\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\260\332\377\377\r\000\000\000 \000\000\000\060\000\000\000p\333\377\377\377\177\000\000\260\332\377\377\377\177\000\000\300\001\000\000\000\000\000\000@K\235\000\000\000\000\000\001\000\000\000\000\000\000\000\021\257\352l\001\000\000\000`\333\377\377\377\177\000\000\021\256M\000\000\000\000\000\003\000\000\000\000\000\000\000 \000\000\000\060\000\000\000p\333\377\377\377\177\000\000\260\332\377\377\377\177\000\000\020\333\377\377\377\177\000\000"...
---Type <return> to continue, or q <return> to quit---
        logCommand = false
        atcmd_msg = "@itemmap Blue_Potion 100\000<;\366\001\000\000\000t\310\350\000\000\000\000\000d\213d\352\377\177\000\000@\001\000\000\000\000\000\000\021\000\000\000\f\000\000\000\000\000\000\000\377\177\000\000@^\236\361\377\177\000\000\310\020\000\000\000\000\000\000\071\061O\000\000\000\000\000\r\000\000\000\026\000\000\000\025\000\000\000c\000\000\000\320\333\377\377\377\177\000\000E\016O\000\000\000\000\000x\334\377\377\377\177\000\000\200\333\377\377\377\177\000\000t\310\350\000\001\000\000\000\n\000\000\000\203\000\000\000u\310\350", '\000' <repeats 21 times>, "d\213d\352\377\177\000\000\021\257\352l\001\000\000\000"...
#5  0x0000000000530202 in pc_process_chat_message (sd=0x1765a30,
    message=0xffffff9c <Address 0xffffff9c out of bounds>) at pc.c:12241
No locals.
#6  0x000000000047308f in clif_process_chat_message (sd=0x1765a30,
    packet=0x7ffff4b567b4, out_buf=0x9d4700 <log_s> "\377\377\377\177z\006",
    out_buflen=256) at clif.c:10266
        srcname = 0x7ffff4b567b8 "GMTeam : @itemmap Blue_Potion 100"
        message = 0x7fffffffdd0a "@itemmap Blue_Potion 100"
        textlen = 1
        __func__ = "clif_process_chat_message"
#7  0x000000000046ce23 in clif_parse_GlobalMessage (fd=11, sd=0x1765a30)
    at clif.c:11178
        full_message = "GMTeam : @itemmap Blue_Potion 100\000l\001\000\000\000@---Type <return> to continue, o
```

**Comment by tlacson7** [comment]
also @itemmap <nameID> 103  . can you try?

**Comment by dastgirp** [comment]
Fixed, will be pushed in a hour.
